stages:
  - validate
  - plan
  - apply

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/terraform-eks  # Diretório do Terraform
  AWS_DEFAULT_REGION: "us-east-1"           # Região da AWS
  TF_BACKEND_BUCKET: "tf-state-777"         # Nome do bucket S3 para o estado do Terraform
  TF_BACKEND_KEY: "app-eks/terraform.tfstate"  # Caminho do arquivo de estado no S3

before_script:
  # Instalar dependências básicas
  - apt-get update && apt-get install -y curl unzip git

  # Instalar Terraform
  - curl -LO https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_linux_amd64.zip
  - unzip terraform_1.5.5_linux_amd64.zip -d /usr/local/bin/
  - terraform --version

  # Instalar AWS CLI
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - ./aws/install
  - aws --version

  # Instalar kubectl
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  - kubectl version --client

  # Instalar Helm
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  - helm version

  # Autenticar na AWS
  - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
  - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
  - aws configure set region ${AWS_DEFAULT_REGION}

validate:
  stage: validate
  script:
    - cd ${TF_ROOT}
    - terraform init -backend-config="bucket=${TF_BACKEND_BUCKET}" -backend-config="key=${TF_BACKEND_KEY}" -backend-config="region=${AWS_DEFAULT_REGION}"
    - terraform plan -var="cidr_block=${CIDR_BLOCK}" -var="project_name=${PROJECT_NAME}" -var="cluster_name=${CLUSTER_NAME}" -var="aws_account_id=${AWS_ACCOUNT_ID}" -input=false -out=tfplan
  artifacts:
    paths:
      - ${TF_ROOT}/tfplan
    
# plan:
#   stage: plan
#   script:
#     - cd ${TF_ROOT}
#     - terraform init -backend-config="bucket=${TF_BACKEND_BUCKET}" -backend-config="key=${TF_BACKEND_KEY}" -backend-config="region=${AWS_DEFAULT_REGION}"
#     - terraform plan \
#         -var="cidr_block=${CIDR_BLOCK}" \
#         -var="project_name=${PROJECT_NAME}" \
#         -var="cluster_name=${CLUSTER_NAME}" \
#         -var="aws_account_id=${AWS_ACCOUNT_ID}" \
#         -input=false \
#         -out=tfplan
#   artifacts:
#     paths:
#       - ${TF_ROOT}/tfplan

apply:
  stage: apply
  script:
    - cd ${TF_ROOT}  # Acessa o diretório do Terraform
    - terraform init -backend-config="bucket=${TF_BACKEND_BUCKET}" -backend-config="key=${TF_BACKEND_KEY}" -backend-config="region=${AWS_DEFAULT_REGION}"
    - terraform apply -input=false tfplan
  when: manual
  only:
    - main