apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
  namespace: app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /  # Diretório no EFS onde os logs serão armazenados
    server: fs-0abaa3a35c1554c52.efs.us-east-2.amazonaws.com  # Substitua pelo DNS do seu EFS
  storageClassName: efs-storage-class
