apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
  namespace: app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /  # dir no EFS onde os logs serão armazenados
    server: fs-0cb997ef897b0eca3.efs.us-east-1.amazonaws.com
  storageClassName: efs-storage-class
