apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-app2
  namespace: app2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /  # Diretório no EFS onde os logs serão armazenados
    server: fs-0e02a664610267b7b.efs.us-east-1.amazonaws.com  # Substitua pelo DNS do seu EFS
  storageClassName: efs-storage-class
