apiVersion: v1
kind: Namespace
metadata:
  name: app2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-app2
  namespace: app2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-storage-class
